In [ ]:
import pandas as pd

ModuleNotFoundError: No module named 'tennis_pipeline'

In [4]:
df = pd.read_csv("../data/processed/backtest_predictions.csv")

In [5]:
df['actual_winner'].value_counts()

actual_winner
0    594
1    575
Name: count, dtype: int64

In [7]:
df['predicted_prob_a'].mean()

np.float64(0.5288949081103507)

In [5]:
import pandas as pd

In [20]:
df = pd.read_csv("../data/backtest/real_2026_odds.csv", sep=";")

In [21]:
df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,B365W,B365L,PSW,PSL,MaxW,MaxL,AvgW,AvgL,BFEW,BFEL
0,1,Brisbane,Brisbane International,04.01.2026,ATP250,Outdoor,Hard,1st Round,3,Tiafoe F.,...,"1,44","2,75","1,52","2,7","1,53","2,95","1,47","2,63","1,53","2,88"
1,1,Brisbane,Brisbane International,04.01.2026,ATP250,Outdoor,Hard,1st Round,3,Tien L.,...,"1,14","5,5","1,2","5,21","1,18","5,5","1,16","5,06","1,19",6
2,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Korda S.,...,"1,5","2,63","1,54","2,64","1,52","2,75","1,48","2,61","1,56","2,74"
3,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Michelsen A.,...,"1,73","2,1","1,73","2,22","1,8","2,2","1,71","2,11","1,75","2,28"
4,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Lehecka J.,...,"1,5","2,63","1,52","2,71","1,57","2,75","1,49","2,56","1,54","2,76"

In [22]:
df['Comment'].value_counts()

Comment
Completed    984
Retired       25
Walkover       7
Name: count, dtype: int64

In [23]:
df = df[~df['Comment'].str.contains("Retired", na=False)]

In [24]:
df = df[~df['Comment'].str.contains("Walkover", na=False)]

In [25]:
df['Comment'].value_counts()

Comment
Completed    984
Name: count, dtype: int64

In [26]:
df = df.dropna(subset=['BFEW'])

In [27]:
df = df.dropna(subset=['BFEL'])

In [28]:
df['Comment'].value_counts()

Comment
Completed    890
Name: count, dtype: int64

In [29]:
df.to_csv("real_2026_odds.csv", index=False)

In [30]:
df['BFEW'].value_counts()

BFEW
1,44    16
1,28    14
1,38    14
1,29    14
1,35    12
        ..
2,74     1
9,6      1
15       1
2,96     1
3,9      1
Name: count, Length: 179, dtype: int64

In [34]:
print(df['BFEW'].dtype)

str

In [35]:
df["BFEW"] = df["BFEW"].str.replace(",", ".").astype(float)
df["BFEL"] = df["BFEL"].str.replace(",", ".").astype(float)

In [36]:
df.to_csv("real_2026_odds.csv", index=False)

In [37]:
df['BFEW'].mean()

np.float64(1.9300786516853932)

In [38]:
df['BFEL'].mean()

np.float64(4.177685393258427)

In [39]:
df = pd.read_csv("../data/backtest/real_2026_odds.csv")
df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,B365W,B365L,PSW,PSL,MaxW,MaxL,AvgW,AvgL,BFEW,BFEL
0,1,Brisbane,Brisbane International,04.01.2026,ATP250,Outdoor,Hard,1st Round,3,Tiafoe F.,...,"1,44","2,75","1,52","2,7","1,53","2,95","1,47","2,63",1.53,2.88
1,1,Brisbane,Brisbane International,04.01.2026,ATP250,Outdoor,Hard,1st Round,3,Tien L.,...,"1,14","5,5","1,2","5,21","1,18","5,5","1,16","5,06",1.19,6.00
2,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Korda S.,...,"1,5","2,63","1,54","2,64","1,52","2,75","1,48","2,61",1.56,2.74
3,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Michelsen A.,...,"1,73","2,1","1,73","2,22","1,8","2,2","1,71","2,11",1.75,2.28
4,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Lehecka J.,...,"1,5","2,63","1,52","2,71","1,57","2,75","1,49","2,56",1.54,2.76

In [40]:
df["PSW"] = df["PSW"].str.replace(",", ".").astype(float)
df["PSL"] = df["PSL"].str.replace(",", ".").astype(float)
df["MaxW"] = df["MaxW"].str.replace(",", ".").astype(float)
df["MaxL"] = df["MaxL"].str.replace(",", ".").astype(float)

In [41]:
df.head()

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,B365W,B365L,PSW,PSL,MaxW,MaxL,AvgW,AvgL,BFEW,BFEL
0,1,Brisbane,Brisbane International,04.01.2026,ATP250,Outdoor,Hard,1st Round,3,Tiafoe F.,...,"1,44","2,75",1.52,2.70,1.53,2.95,"1,47","2,63",1.53,2.88
1,1,Brisbane,Brisbane International,04.01.2026,ATP250,Outdoor,Hard,1st Round,3,Tien L.,...,"1,14","5,5",1.20,5.21,1.18,5.50,"1,16","5,06",1.19,6.00
2,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Korda S.,...,"1,5","2,63",1.54,2.64,1.52,2.75,"1,48","2,61",1.56,2.74
3,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Michelsen A.,...,"1,73","2,1",1.73,2.22,1.80,2.20,"1,71","2,11",1.75,2.28
4,1,Brisbane,Brisbane International,05.01.2026,ATP250,Outdoor,Hard,1st Round,3,Lehecka J.,...,"1,5","2,63",1.52,2.71,1.57,2.75,"1,49","2,56",1.54,2.76

In [42]:
df.to_csv("real_2026_odds.csv", index=False)